export const SITE_SETTING = {
  DISABLE_REGISTER: "DISABLE_REGISTER",
  FORBIDDEN_NAMES: "FORBIDDEN_NAMES",
  DISABLE_QUEUE_JOBS: "DISABLE_QUEUE_JOBS",
  LAST_QUEUES_EXECUTION: "LAST_QUEUES_EXECUTION",
  DISABLE_RECORDINGS: "DISABLE_RECORDINGS",
} as const;
