export const USER_SETTING = {
  STORE_PAST_STREAMS: "STORE_PAST_STREAMS",
  DEFAULT_VISIBILITY_UNSAVED_RECORDINGS:
    "DEFAULT_VISIBILITY_UNSAVED_RECORDINGS",
  IS_ONLINE: "IS_ONLINE",
  LAST_ONLINE: "LAST_ONLINE",
} as const;
